//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    public enum Должность
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Должность.Руководитель CustomAttributes)

        // *** End programmer edit section *** (Должность.Руководитель CustomAttributes)
        Руководитель,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Должность.Разработчик CustomAttributes)

        // *** End programmer edit section *** (Должность.Разработчик CustomAttributes)
        Разработчик,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Должность.Экономист CustomAttributes)

        // *** End programmer edit section *** (Должность.Экономист CustomAttributes)
        Экономист,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Должность.Менеджер CustomAttributes)

        // *** End programmer edit section *** (Должность.Менеджер CustomAttributes)
        Менеджер,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Должность.Тестировщик CustomAttributes)

        // *** End programmer edit section *** (Должность.Тестировщик CustomAttributes)
        Тестировщик,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Должность.Бухгалтер CustomAttributes)

        // *** End programmer edit section *** (Должность.Бухгалтер CustomAttributes)
        Бухгалтер,
    }
}
