//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Журнал.
    /// </summary>
    // *** Start programmer edit section *** (Журнал CustomAttributes)

    // *** End programmer edit section *** (Журнал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖурналE", new string[] {
            "Статус",
            "Обязательный as \'Обязательный\'",
            "Оценка as \'Оценка\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Курс as \'Курс\'",
            "Курс.Название as \'Название\'"})]
    [View("ЖурналL", new string[] {
            "Статус",
            "Обязательный as \'Обязательный\'",
            "Оценка as \'Оценка\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Курс.Название as \'Название\'"})]
    [View("JournalView", new string[] {
            "Статус",
            "Обязательный as \'Обязательный\'",
            "Оценка as \'Оценка\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Курс.Название as \'Название\'"})]
    public class Журнал : ICSSoft.STORMNET.DataObject
    {

        private IIS.EmployeeCourses.СтатусКурса fСтатус;

        private bool fОбязательный;

        private int fОценка;

        private IIS.EmployeeCourses.Сотрудник fСотрудник;

        private IIS.EmployeeCourses.Курс fКурс;

        // *** Start programmer edit section *** (Журнал CustomMembers)

        // *** End programmer edit section *** (Журнал CustomMembers)


        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Статус CustomAttributes)

        // *** End programmer edit section *** (Журнал.Статус CustomAttributes)
        [NotNull()]
        public virtual IIS.EmployeeCourses.СтатусКурса Статус
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Статус Get start)

                // *** End programmer edit section *** (Журнал.Статус Get start)
                IIS.EmployeeCourses.СтатусКурса result = this.fСтатус;
                // *** Start programmer edit section *** (Журнал.Статус Get end)

                // *** End programmer edit section *** (Журнал.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Статус Set start)

                // *** End programmer edit section *** (Журнал.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Журнал.Статус Set end)

                // *** End programmer edit section *** (Журнал.Статус Set end)
            }
        }

        /// <summary>
        /// Обязательный.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Обязательный CustomAttributes)

        // *** End programmer edit section *** (Журнал.Обязательный CustomAttributes)
        public virtual bool Обязательный
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Обязательный Get start)

                // *** End programmer edit section *** (Журнал.Обязательный Get start)
                bool result = this.fОбязательный;
                // *** Start programmer edit section *** (Журнал.Обязательный Get end)

                // *** End programmer edit section *** (Журнал.Обязательный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Обязательный Set start)

                // *** End programmer edit section *** (Журнал.Обязательный Set start)
                this.fОбязательный = value;
                // *** Start programmer edit section *** (Журнал.Обязательный Set end)

                // *** End programmer edit section *** (Журнал.Обязательный Set end)
            }
        }

        /// <summary>
        /// Оценка.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Оценка CustomAttributes)

        // *** End programmer edit section *** (Журнал.Оценка CustomAttributes)
        public virtual int Оценка
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Оценка Get start)

                // *** End programmer edit section *** (Журнал.Оценка Get start)
                int result = this.fОценка;
                // *** Start programmer edit section *** (Журнал.Оценка Get end)

                // *** End programmer edit section *** (Журнал.Оценка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Оценка Set start)

                // *** End programmer edit section *** (Журнал.Оценка Set start)
                this.fОценка = value;
                // *** Start programmer edit section *** (Журнал.Оценка Set end)

                // *** End programmer edit section *** (Журнал.Оценка Set end)
            }
        }

        /// <summary>
        /// Журнал.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Журнал.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.EmployeeCourses.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Сотрудник Get start)

                // *** End programmer edit section *** (Журнал.Сотрудник Get start)
                IIS.EmployeeCourses.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Журнал.Сотрудник Get end)

                // *** End programmer edit section *** (Журнал.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Сотрудник Set start)

                // *** End programmer edit section *** (Журнал.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Журнал.Сотрудник Set end)

                // *** End programmer edit section *** (Журнал.Сотрудник Set end)
            }
        }

        /// <summary>
        /// Журнал.
        /// </summary>
        // *** Start programmer edit section *** (Журнал.Курс CustomAttributes)

        // *** End programmer edit section *** (Журнал.Курс CustomAttributes)
        [PropertyStorage(new string[] {
                "Курс"})]
        [NotNull()]
        public virtual IIS.EmployeeCourses.Курс Курс
        {
            get
            {
                // *** Start programmer edit section *** (Журнал.Курс Get start)

                // *** End programmer edit section *** (Журнал.Курс Get start)
                IIS.EmployeeCourses.Курс result = this.fКурс;
                // *** Start programmer edit section *** (Журнал.Курс Get end)

                // *** End programmer edit section *** (Журнал.Курс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Журнал.Курс Set start)

                // *** End programmer edit section *** (Журнал.Курс Set start)
                this.fКурс = value;
                // *** Start programmer edit section *** (Журнал.Курс Set end)

                // *** End programmer edit section *** (Журнал.Курс Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ЖурналE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурналE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурналE", typeof(IIS.EmployeeCourses.Журнал));
                }
            }

            /// <summary>
            /// "ЖурналL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурналL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурналL", typeof(IIS.EmployeeCourses.Журнал));
                }
            }
            public static ICSSoft.STORMNET.View JournalView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("JournalView", typeof(IIS.EmployeeCourses.Журнал));
                }
            }
        }
    }
}
