//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Занятие.
    /// </summary>
    // *** Start programmer edit section *** (Занятие CustomAttributes)

    // *** End programmer edit section *** (Занятие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗанятиеE", new string[] {
            "ДатаВремя as \'Дата и время\'",
            "Тема as \'Тема\'",
            "Описание as \'Описание\'"})]
    public class Занятие : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВремя;
        
        private string fТема;
        
        private string fОписание;
        
        private IIS.EmployeeCourses.Курс fКурс;
        
        // *** Start programmer edit section *** (Занятие CustomMembers)

        // *** End programmer edit section *** (Занятие CustomMembers)

        
        /// <summary>
        /// ДатаВремя.
        /// </summary>
        // *** Start programmer edit section *** (Занятие.ДатаВремя CustomAttributes)

        // *** End programmer edit section *** (Занятие.ДатаВремя CustomAttributes)
        public virtual System.DateTime ДатаВремя
        {
            get
            {
                // *** Start programmer edit section *** (Занятие.ДатаВремя Get start)

                // *** End programmer edit section *** (Занятие.ДатаВремя Get start)
                System.DateTime result = this.fДатаВремя;
                // *** Start programmer edit section *** (Занятие.ДатаВремя Get end)

                // *** End programmer edit section *** (Занятие.ДатаВремя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Занятие.ДатаВремя Set start)

                // *** End programmer edit section *** (Занятие.ДатаВремя Set start)
                this.fДатаВремя = value;
                // *** Start programmer edit section *** (Занятие.ДатаВремя Set end)

                // *** End programmer edit section *** (Занятие.ДатаВремя Set end)
            }
        }
        
        /// <summary>
        /// Тема.
        /// </summary>
        // *** Start programmer edit section *** (Занятие.Тема CustomAttributes)

        // *** End programmer edit section *** (Занятие.Тема CustomAttributes)
        [StrLen(255)]
        public virtual string Тема
        {
            get
            {
                // *** Start programmer edit section *** (Занятие.Тема Get start)

                // *** End programmer edit section *** (Занятие.Тема Get start)
                string result = this.fТема;
                // *** Start programmer edit section *** (Занятие.Тема Get end)

                // *** End programmer edit section *** (Занятие.Тема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Занятие.Тема Set start)

                // *** End programmer edit section *** (Занятие.Тема Set start)
                this.fТема = value;
                // *** Start programmer edit section *** (Занятие.Тема Set end)

                // *** End programmer edit section *** (Занятие.Тема Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Занятие.Описание CustomAttributes)

        // *** End programmer edit section *** (Занятие.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Занятие.Описание Get start)

                // *** End programmer edit section *** (Занятие.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Занятие.Описание Get end)

                // *** End programmer edit section *** (Занятие.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Занятие.Описание Set start)

                // *** End programmer edit section *** (Занятие.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Занятие.Описание Set end)

                // *** End programmer edit section *** (Занятие.Описание Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.EmployeeCourses.Курс.
        /// </summary>
        // *** Start programmer edit section *** (Занятие.Курс CustomAttributes)

        // *** End programmer edit section *** (Занятие.Курс CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Курс"})]
        public virtual IIS.EmployeeCourses.Курс Курс
        {
            get
            {
                // *** Start programmer edit section *** (Занятие.Курс Get start)

                // *** End programmer edit section *** (Занятие.Курс Get start)
                IIS.EmployeeCourses.Курс result = this.fКурс;
                // *** Start programmer edit section *** (Занятие.Курс Get end)

                // *** End programmer edit section *** (Занятие.Курс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Занятие.Курс Set start)

                // *** End programmer edit section *** (Занятие.Курс Set start)
                this.fКурс = value;
                // *** Start programmer edit section *** (Занятие.Курс Set end)

                // *** End programmer edit section *** (Занятие.Курс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗанятиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗанятиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗанятиеE", typeof(IIS.EmployeeCourses.Занятие));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Занятие.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗанятие CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗанятие CustomAttributes)
    public class DetailArrayOfЗанятие : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.EmployeeCourses.DetailArrayOfЗанятие members)

        // *** End programmer edit section *** (IIS.EmployeeCourses.DetailArrayOfЗанятие members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Занятие by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Занятие.
        /// </summary>
        public DetailArrayOfЗанятие(IIS.EmployeeCourses.Курс fКурс) : 
                base(typeof(Занятие), ((ICSSoft.STORMNET.DataObject)(fКурс)))
        {
        }
        
        public IIS.EmployeeCourses.Занятие this[int index]
        {
            get
            {
                return ((IIS.EmployeeCourses.Занятие)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.EmployeeCourses.Занятие dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
