//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Категория.
    /// </summary>
    // *** Start programmer edit section *** (Категория CustomAttributes)

    // *** End programmer edit section *** (Категория CustomAttributes)
    public enum Категория
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Категория.БД CustomAttributes)

        // *** End programmer edit section *** (Категория.БД CustomAttributes)
        БД,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Категория.ИС CustomAttributes)

        // *** End programmer edit section *** (Категория.ИС CustomAttributes)
        ИС,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Категория.ЖЦПО CustomAttributes)

        // *** End programmer edit section *** (Категория.ЖЦПО CustomAttributes)
        ЖЦПО,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Категория.ТРИЗ CustomAttributes)

        // *** End programmer edit section *** (Категория.ТРИЗ CustomAttributes)
        ТРИЗ,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Категория.Программирование CustomAttributes)

        // *** End programmer edit section *** (Категория.Программирование CustomAttributes)
        Программирование,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Категория.Финансы CustomAttributes)

        // *** End programmer edit section *** (Категория.Финансы CustomAttributes)
        Финансы,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Категория.Прочее CustomAttributes)

        // *** End programmer edit section *** (Категория.Прочее CustomAttributes)
        Прочее,
    }
}
