//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус курса.
    /// </summary>
    // *** Start programmer edit section *** (СтатусКурса CustomAttributes)

    // *** End programmer edit section *** (СтатусКурса CustomAttributes)
    public enum СтатусКурса
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусКурса.Ожидается CustomAttributes)

        // *** End programmer edit section *** (СтатусКурса.Ожидается CustomAttributes)
        Ожидается,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусКурса.Слушается CustomAttributes)

        // *** End programmer edit section *** (СтатусКурса.Слушается CustomAttributes)
        Слушается,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусКурса.Окончен CustomAttributes)

        // *** End programmer edit section *** (СтатусКурса.Окончен CustomAttributes)
        Окончен,
    }
}
