//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СтатусЗаявки.
    /// </summary>
    // *** Start programmer edit section *** (СтатусЗаявки CustomAttributes)

    // *** End programmer edit section *** (СтатусЗаявки CustomAttributes)
    public enum СтатусЗаявки
    {
        
        // *** Start programmer edit section *** (СтатусЗаявки.Ожидается CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаявки.Ожидается CustomAttributes)
        Ожидается,
        
        // *** Start programmer edit section *** (СтатусЗаявки.Принята CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаявки.Принята CustomAttributes)
        Принята,
        
        // *** Start programmer edit section *** (СтатусЗаявки.Отклонена CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаявки.Отклонена CustomAttributes)
        Отклонена,
    }
}
