//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип курса.
    /// </summary>
    // *** Start programmer edit section *** (ТипКурса CustomAttributes)

    // *** End programmer edit section *** (ТипКурса CustomAttributes)
    public enum ТипКурса
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипКурса.Семинар CustomAttributes)

        // *** End programmer edit section *** (ТипКурса.Семинар CustomAttributes)
        Семинар,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипКурса.Тренинг CustomAttributes)

        // *** End programmer edit section *** (ТипКурса.Тренинг CustomAttributes)
        Тренинг,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипКурса.Лекция CustomAttributes)

        // *** End programmer edit section *** (ТипКурса.Лекция CustomAttributes)
        Лекция,
    }
}
