//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EmployeeCourses
{
    using ICSSoft.STORMNET;
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДобавлениеСотрудникаВБазу.
    /// </summary>
    // *** Start programmer edit section *** (ДобавлениеСотрудникаВБазу CustomAttributes)

    // *** End programmer edit section *** (ДобавлениеСотрудникаВБазу CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ДобавлениеСотрудникаВБазу : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ДобавлениеСотрудникаВБазу CustomMembers)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateСотрудник(IIS.EmployeeCourses.Сотрудник UpdatedObject)
        {
            DataObject[] temp = new DataObject[0];
            return temp;
        }
        // *** End programmer edit section *** (ДобавлениеСотрудникаВБазу CustomMembers)

    }
}
