//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace IIS.EmployeeCourses
{
    /// <summary>
    /// Queries class.
    /// </summary>
    /// <remarks>
    /// Non-Auto-generated class.
    /// </remarks>
    public partial class Queiries
    {
        //объявление класса запросов
    }
}
