<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="KursE.aspx.cs" Inherits="IIS.EmployeeCourses.КурсE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass %> <%= Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Курс</h2>
        <div class="<%= Constants.FormToolbarCssClass %> <%= Constants.EditFormToolbarCssClass %> <%= Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass %> <%= Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlНазваниеLabel" runat="server" Text="Название" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlНазвание" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlНазваниеValidator" runat="server" ControlToValidate="ctrlНазвание"
ErrorMessage="Не указано: Название" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаНачалаLabel" runat="server" Text="Дата начала" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаНачала" runat="server"/>
</div>
<asp:RequiredFieldValidator ID="ctrlДатаНачалаValidator" runat="server" ControlToValidate="ctrlДатаНачала"
ErrorMessage="Не указано: ДатаНачала" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаКонцаLabel" runat="server" Text="Дата конца" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаКонца" runat="server"/>
</div>
<asp:RequiredFieldValidator ID="ctrlДатаКонцаValidator" runat="server" ControlToValidate="ctrlДатаКонца"
ErrorMessage="Не указано: ДатаКонца" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlТипLabel" runat="server" Text="Тип" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlТип" CssClass="descTxt" runat="server">
	<asp:ListItem>Семинар</asp:ListItem>
<asp:ListItem>Тренинг</asp:ListItem>
<asp:ListItem>Лекция</asp:ListItem>

</asp:DropDownList>
<asp:RequiredFieldValidator ID="ctrlТипValidator" runat="server" ControlToValidate="ctrlТип"
ErrorMessage="Не указано: Тип" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОчныйLabel" runat="server" Text="Очный" EnableViewState="False">
</asp:Label>
<asp:CheckBox ID="ctrlОчный" CssClass="descTxt" runat="server" Text=""/>
</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlКатегорияLabel" runat="server" Text="Категория" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlКатегория" CssClass="descTxt" runat="server">
	<asp:ListItem>БД</asp:ListItem>
<asp:ListItem>ИС</asp:ListItem>
<asp:ListItem>ЖЦПО</asp:ListItem>
<asp:ListItem>ТРИЗ</asp:ListItem>
<asp:ListItem>Программирование</asp:ListItem>
<asp:ListItem>Финансы</asp:ListItem>
<asp:ListItem>Прочее</asp:ListItem>

</asp:DropDownList>
<asp:RequiredFieldValidator ID="ctrlКатегорияValidator" runat="server" ControlToValidate="ctrlКатегория"
ErrorMessage="Не указано: Категория" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlОписаниеLabel" runat="server" Text="Описание" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlОписание" runat="server">
</asp:TextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСтоимостьLabel" runat="server" Text="Стоимость" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlСтоимость" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>

<asp:RequiredFieldValidator ID="ctrlСтоимостьValidator" runat="server" ControlToValidate="ctrlСтоимость"
ErrorMessage="Не указано: Стоимость" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlМестоПроведенияLabel" runat="server" Text="Место проведения" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlМестоПроведения" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlМестоПроведенияValidator" runat="server" ControlToValidate="ctrlМестоПроведения"
ErrorMessage="Не указано: МестоПроведения" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<asp:ScriptManager ID="ScriptManager1" runat="server" >
</asp:ScriptManager>

<div style="clear: left">
	<ac:AjaxGroupEdit ID="ctrlЗанятие" runat="server" ReadOnly="false" />
</div>
<br/>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
