/*flexberryautogenerated="true"*/
namespace IIS.EmployeeCourses
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class MyCourses : BaseListForm<Курс>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
    }
}
